### ISSUE TITLE
ties elements

### ISSUE THREAD

**Issue by rjpbonnal** [changyaochen/rbo#10]
is it possible to define ties in both lists ?

**Comment by f4lco** [comment]
What exactly means ties "in both lists"?

Given two lists A, B: The same element may appear at the same index in A and B, e.g.

```
A = [4, 5, 6]
B = [3, 5, 7]
````
tie at list index 1. This type of tie can be processed by RBO in principle and also with this implementation, I believe. Conceptually, repetitions of the same element in either A or B are not permissible. The individual lists must not contain duplicates.

@changyaochen I see that *rbo_ext* explicitly handles ties. Is the same true for *rbo*?

**Comment by rjpbonnal** [comment]
So, guess that I have two ranked lists with more than 100 elements each.
Let' say that I do not want to use the strict ranks for each list, instead I would like to aggregate elements in each list by ranges suchs the first ten elments have the same "rank" 1, then the second ten items are in position 2, the third ten items are in position 3 etc.

```
A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12,13]
B = [2, 1, 3, 7, 4, 6, 5, 8, 10, 9, 12, 11, 13]
``` 
```
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12,13]]
B = [[2, 1, 3], [7, 4, 6], [5, 8, 10], [9, 12, 11, 13]]
```

I am not sure if RBO can handle this, but I found https://github.com/dlukes/rbo

**Comment by f4lco** [comment]
For this implementation, I think the element types of the lists must be hashable, e.g., int, string, or even tuple.

```python
>>> rbo.RankingSimilarity([(1, 2, 3)], [(4, 5, 6)]).rbo()
0
>>> rbo.RankingSimilarity([(1, 2, 3)], [(1, 2, 3)]).rbo()
1.0
```

That rules out lists, sets, and dicts as element types for comparison. Glad you found an implementation which allows that.
