### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by frankier** [changyaochen/rbo#11]
Would it be possible to publish this to PyPI? The reason is that git dependencies cannot be used from packages published to PyPI so it means this can only be used from applications and not libraries.

**Comment by f4lco** [comment]
I previously contributed and I'm in favor of doing so. Publishing this library might help reach a wider audience and mitigate troubles with installing git dependencies (I have mixed experiences with git support in pip, poetry). @changyaochen would you like to follow up on your last commit, "getting ready for pypi"?

**Comment by changyaochen** [comment]
Thanks, @f4lco and @frankier to revive this effort! I've created a PR as the penultimate step to publishing on pypi.
