### ISSUE TITLE
Parameterize p

### ISSUE THREAD

**Issue by crude-coder** [changyaochen/rbo#13]
I see that `self.p` of the `RankingSimilarity` Class is locked into `0.5`. Could we parameterize that value before the next update, or perhaps get reasoning why it’s locked at that value?

**Comment by crude-coder** [comment]
I see it parameterized in a class function and updated there

**Comment by f4lco** [comment]
@crude-coder thank you for reaching out anyway. Suggestions are always welcome. We're actively working towards availability on PyPI, just in case this is relevant to your current project.
